version: "3.7"

services:
  app:
    image: koinotice/pk 
    ports: 
      - 10000:10000 
    volumes:
      - "./src/:/pagekit"
    networks:
      - app
  web:
    image: stefanprodan/caddy:latest
    volumes:
      - "./docker/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./src/:/var/www/html"
    networks:
      - app
    ports:
      - 80:2015
   


networks:
  app: